server:
  host: 0.0.0.0
  port: 8080

api:
  defaultLimit: 10

proxy:
  healthChecker:
    interval: 15s # интервал проверки бэкенд серверов
    healthCheckTimeout: 5s 
  timeout: 5s
  keepAlive: 30s
  idleConnTimeout: 100s
  maxIdleConns: 100
  maxIdleConnsPerHost: 10
  TLSHandshakeTimeout: 5s

balancer:
  strategy: round_robin # round_robin, random 
  backends:
    - http://localhost:8081
    - http://localhost:8082
    - http://localhost:8083

bucket:
  capacity: 10
  refill:
    interval: 1m # периодичность пополения
    amount:   1

db:
  host: localhost
  port: 5432
  user: postgres
  password: changeme
  dbname: gopher_equalizer
  sslmode: disable
  schema: gopherEqualizer
  connectRetries: 5
  connectRetryDelay: 5s # время
  pool:
    maxConns: 10
    minConns: 5
    maxConnLifetime: 10s # 1m, 1h
    maxConnIdleTime: 5s
    healthCheckPeriod: 5s

logger:
  level: "debug"
  development: true
  encoding: "json"
  outputPaths: ["stdout"]
  errorOutputPaths: ["stderr"]
  encoderConfig:
    messageKey: "message"
    levelKey: "level"
    timeKey: "timestamp"
    encodeLevel: "lowercase"